/**
 * Git transport.
 *
 * One publish is one throwaway repository: a temp directory gets a fresh `git
 * init`, the clean-copy files are hard-linked into it, one commit is created, and
 * that commit is force-pushed to the plugin's repository. The result is a
 * repository whose history is a readable sequence of snapshots rather than a
 * mirror of a working tree that happens to live in this workspace — and the
 * workspace plugin directory itself never grows a `.git`, so nothing about the
 * local layout leaks into what is published.
 *
 * The token never reaches a command line, an argv array, or a remote URL. Git
 * asks for credentials through a helper that reads a generated file; the token
 * exists only inside that helper's own memory and in the JSON payload it writes
 * back on stdout.
 */

import { execFile } from 'node:child_process'
import { copyFileSync, existsSync, linkSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'

import { USER_CONFIG } from './config.js'

/**
 * Replace every occurrence of the token in a string with a mask.
 *
 * @param {string} text - text that may embed the token.
 * @param {string | undefined} token - the secret to mask.
 * @returns {string} the masked text.
 */
export function maskSecret(text, token) {
	let out = String(text ?? '')
	if (typeof token === 'string' && token.length >= 8) {
		out = out.split(token).join('***')
	}
	return out.replace(/(https?:\/\/)[^@\s/]+:[^@\s/]+@/gi, '$1***@')
}

/**
 * Run one git command.
 *
 * @param {object} options - invocation inputs.
 * @param {string} options.git - git executable.
 * @param {string[]} options.args - arguments; never contains a secret.
 * @param {string} [options.cwd] - working directory.
 * @param {Record<string, string>} [options.env] - extra environment entries.
 * @param {string} [options.token] - a secret to strip from any error text.
 * @param {number} [options.timeoutMs] - hard timeout.
 * @returns {Promise<{ stdout: string, stderr: string }>} captured output.
 */
function run({ git, args, cwd, env, token, timeoutMs = 180_000 }) {
	return new Promise((resolve, reject) => {
		execFile(
			git,
			args,
			{
				cwd,
				timeout: timeoutMs,
				maxBuffer: 32 * 1024 * 1024,
				windowsHide: true,
				env: {
					...process.env,
					// Deterministic, non-interactive, and independent of whatever the
					// user's global git config happens to say about credentials.
					GIT_TERMINAL_PROMPT: '0',
					GIT_CONFIG_NOSYSTEM: '1',
					LC_ALL: 'C',
					...env,
				},
			},
			(error, stdout, stderr) => {
				if (error === null || error === undefined) {
					resolve({ stdout: String(stdout), stderr: String(stderr) })
					return
				}
				if (error.code === 'ENOENT') {
					reject(new Error(`找不到 git 可执行文件「${git}」。请安装 Git，或在 sync.config.json 的 git.executable 里写绝对路径。`))
					return
				}
				const detail = maskSecret(`${stderr || stdout || error.message}`.trim(), token)
				const failure = new Error(`git ${args[0]} 失败（退出码 ${error.code ?? '?'}）：\n${detail}`)
				failure.gitStderr = detail
				failure.exitCode = error.code
				reject(failure)
			},
		)
	})
}

/**
 * Source text of the credential helper written into every staging directory.
 *
 * Git invokes it as `<command> get` and reads `username=` / `password=` lines
 * from stdout. Anything else — `store`, `erase`, a missing file — exits quietly,
 * because a helper that chats on stderr makes every git error unreadable.
 *
 * @param {string} tokenFile - absolute path of the JSON file holding the token.
 * @returns {string} a complete ESM script.
 */
export function credentialHelperSource(tokenFile) {
	const literal = JSON.stringify(tokenFile)
	return `// Generated by @local/dsh-github-sync. Deleted with its staging directory.
import { readFileSync } from 'node:fs'

const FILE = ${literal}

function token() {
	try {
		const raw = JSON.parse(readFileSync(FILE, 'utf8'))
		const value = typeof raw?.github?.token === 'string' ? raw.github.token.trim() : ''
		return value === '' ? undefined : value
	} catch {
		return undefined
	}
}

const op = process.argv[2]
if (op === 'get') {
	const value = token()
	if (value !== undefined) {
		process.stdout.write('username=x-access-token\\n')
		process.stdout.write('password=' + value + '\\n')
	}
}
process.exit(0)
`
}

/**
 * Publish one manifest to one repository.
 *
 * @param {object} options - publish inputs.
 * @param {Manifest} options.manifest - the clean-copy manifest to publish.
 * @param {string} options.repository - `owner/name` on GitHub.
 * @param {string} options.branch - branch to force-push.
 * @param {string} options.commitMessage - the commit subject.
 * @param {string} options.git - git executable.
 * @param {string} options.userName - committer name recorded in the commit.
 * @param {string} options.userEmail - committer email recorded in the commit.
 * @param {string | undefined} options.token - GitHub token used for HTTPS auth.
 * @param {string} options.tokenFile - file the credential helper reads.
 * @param {boolean} [options.dryRun] - stage and commit, but push nowhere.
 * @param {string} [options.remoteUrl] - override the remote. Only a local path is
 *   meaningful here: it exists so the full push path can be exercised end to end
 *   against a throwaway bare repository during development. A GitHub remote is
 *   always derived from `repository`, so no caller can point a real push at an
 *   unintended host by accident.
 * @returns {Promise<PublishResult>} what was committed, and what was pushed.
 */
export async function publish({ manifest, repository, branch, commitMessage, git, userName, userEmail, token, tokenFile, dryRun = false, remoteUrl }) {
	if (manifest.files.length === 0) {
		throw new Error(`干净副本里一个文件都没有：${manifest.dir}\n（检查 include 白名单，或 sync.config.json 的排除规则）`)
	}

	const base = join(tmpdir(), 'dsh-github-sync')
	mkdirSync(base, { recursive: true })
	const work = join(base, `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`)
	mkdirSync(work, { recursive: true })

	try {
		// 1. Lay out the clean copy, hard-linking when the volume allows it so a
		//    large plugin costs no copy time and no extra disk.
		let copied = 0
		let linked = 0
		for (const file of manifest.files) {
			const target = join(work, ...file.path.split('/'))
			mkdirSync(dirname(target), { recursive: true })
			const source = join(manifest.dir, ...file.path.split('/'))
			try {
				linkSync(source, target)
				linked++
			} catch {
				copyFileSync(source, target)
				copied++
			}
		}

		const common = { git, cwd: work, token }
		await run({ ...common, args: ['init', '--quiet', '--initial-branch', branch] })
		await run({ ...common, args: ['config', 'user.name', userName] })
		await run({ ...common, args: ['config', 'user.email', userEmail] })
		await run({ ...common, args: ['config', 'core.autocrlf', 'false'] })
		await run({ ...common, args: ['add', '-A', '--force', '.'] })

		const staged = await run({ ...common, args: ['diff', '--cached', '--name-only'] })
		const stagedFiles = staged.stdout.split('\n').map((line) => line.trim()).filter((line) => line !== '')
		if (stagedFiles.length === 0) {
			throw new Error(`暂存区是空的，无法提交：${manifest.dir}`)
		}

		const commit = await run({ ...common, args: ['commit', '--quiet', '--no-gpg-sign', '-m', String(commitMessage)] })
		const head = await run({ ...common, args: ['rev-parse', 'HEAD'] })
		const sha = head.stdout.trim()

		if (dryRun) {
			return {
				sha,
				branch,
				files: stagedFiles.length,
				linked,
				copied,
				work,
				pushed: false,
				commitOutput: `${commit.stdout}${commit.stderr}`.trim(),
			}
		}

		if (typeof remoteUrl === 'string' && remoteUrl !== '') {
			// Local-endpoint exercise path: no credential helper, no token, no host
			// that needs authorizing.
			await run({ ...common, args: ['remote', 'add', 'origin', remoteUrl] })
		} else {
			if (typeof token !== 'string' || token.trim() === '') {
				throw new Error(
					'没有可用的 GitHub token，无法推送。\n' +
						'把 token 写进 %USERPROFILE%\\.dsh\\github-sync\\config.json 的 github.token，或设置环境变量 GITHUB_TOKEN。',
				)
			}

			// 2. Credentials. The helper is written after the commit, so it can never be
			//    staged, and it disappears with the staging directory. The token reaches
			//    git as the helper's stdout payload, never as an argument or a URL.
			const helper = join(work, '.git-credential-dsh.mjs')
			writeFileSync(helper, credentialHelperSource(tokenFile), 'utf8')
			await run({ ...common, args: ['config', 'credential.helper', ''] })
			await run({ ...common, args: ['config', '--add', 'credential.helper', `!"${process.execPath}" "${helper}"`] })
			await run({ ...common, args: ['config', 'credential.useHttpPath', 'true'] })

			await run({ ...common, args: ['remote', 'add', 'origin', `https://github.com/${repository}.git`] })
		}

		// 3. Force-push the snapshot. Force is intentional: the repository is a
		//    publication of this manifest, not a merge target.
		const push = await run({
			...common,
			args: ['push', '--force', 'origin', `HEAD:refs/heads/${branch}`],
			token,
			timeoutMs: 600_000,
		})

		return {
			sha,
			branch,
			files: stagedFiles.length,
			linked,
			copied,
			work,
			pushed: true,
			pushOutput: `${push.stdout}${push.stderr}`.trim(),
			commitOutput: `${commit.stdout}${commit.stderr}`.trim(),
		}
	} finally {
		if (existsSync(work)) {
			try {
				rmSync(work, { recursive: true, force: true })
			} catch {
				// A leftover temp directory is not worth failing a successful push over.
			}
		}
	}
}

/**
 * Locate the installed credential file so the helper knows where to read.
 *
 * @returns {string} absolute path of the user configuration file.
 */
export function defaultTokenFile() {
	return USER_CONFIG
}

export default publish